name: Build & Deploy WebGL to itch.io

on:
  push:
    branches: [ "main","Colin" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build WebGL (activation happens automatically)
      - name: Build WebGL (generate activation file)
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_ACTIVATION_FILE: true
        with:
          unityVersion: 6000.0.57f1
          targetPlatform: WebGL
          buildName: WebGL
          buildsPath: build
          unityLicensingServer: false
          skipActivation: false



      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/*.cs') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: unity-activation
          path: Unity_v6000*.alf


      - name: Install butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip -d butler
          sudo mv butler/butler /usr/local/bin/butler
          butler -V

      - name: Push to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}
        run: |
          butler push build/WebGL sleepydragongames/GGJ2026:web
