name: Build & Deploy WebGL to itch.io

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build WebGL (activation happens automatically)
      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}   
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          
        with:
          unityVersion: 6000.0.57f1
          targetPlatform: WebGL
          buildName: WebGL
          buildsPath: build

          
      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
              Library-${{ runner.os }}-


      - name: Install butler
        run: |
          for i in {1..5}; do
            curl -L --retry 5 --retry-delay 2 -o butler.zip \
              https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default && break
          done
          unzip butler.zip -d butler
          sudo install butler/butler /usr/local/bin/butler
          butler -V



      - name: Push to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}
        run: |
          echo "Key length: ${#BUTLER_API_KEY}"
          ls -R build
          butler push build/WebGL two-nerds-studios/quest-for-the-mask-of-genomac:web
