name: Build & Deploy WebGL to itch.io

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Activate Unity license
      - name: Activate Unity
        uses: game-ci/unity-activate@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      # Build WebGL
      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 6000.0.0f1
          targetPlatform: WebGL
          buildName: WebGL
          buildPath: build

      # Install butler
      - name: Install butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip -d butler
          sudo mv butler/butler /usr/local/bin/butler
          butler -V

      # Upload to itch.io
      - name: Push to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}
        run: |
          butler push build/WebGL sleepydragongames/GGJ2026:web
